### ISSUE TITLE
BrowserViz error when attempting to run basic example

### ISSUE THREAD

**Issue by kyleweise** [paul-shannon/RCyjs#3]
Hello! I am very much interested in using this package to incorporate cytospace.js network visualizations into a Shiny app. I am trying to run the first example given in the vignette and I am running into an error. I try:

```
source("https://bioconductor.org/biocLite.R")
biocLite("RCyjs")
library(RCyjs)

g <- simpleDemoGraph()
noaNames(g)
edaNames(g)
noa(g, "type")
noa(g, "lfc")
eda(g, "edgeType")
eda(g, "score")
g <- simpleDemoGraph()
rcy <- RCyjs(portRange=9047:9067, quiet=TRUE, graph=g);
title <- "simple graph"
setBrowserWindowTitle(rcy, title))
```

and I get an error on the ```RCyjs(...)``` line that reads:
**Error in file.exists(browserFile) : argument "browserFile" is missing, with no default**

Would appreciate any help you can provide on this. Have not been able to find and solutions so far.

Thanks!

-Kyle

**Comment by paul-shannon** [comment]
Thanks for the bug report, @kyleweise 
This is fixed as of Saturday.   travis/ci testing coming soon, so that I will catch these errors early.
